name: UnifiedImaging
favicon: null
layout_spectrum: 0.9081208982970566
typography_spectrum: 0.9760015141218901
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#888888'
    - '#6ec6ea'
    - '#e1e1e1'
    - '#a5a5a5'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
