typography_spectrum: 0.9760015141218901
color:
  brandColors:
    - '#ffffff'
    - '#888888'
    - '#6ec6ea'
    - '#e1e1e1'
    - '#a5a5a5'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.35456
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c524856a-6eb8-4e67-ae27-c4703168c93e.eps
name: Unified Imaging
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Unified Imaging
description: ''
purpose:
  - type: contact
    url: 'mailto:bswift@unified-imaging.com'
    label: Unify Your Practice
